### ISSUE TITLE
Using with gradle

### ISSUE THREAD

**Issue by mrZizik** [jbuhacoff/nodejs-mybc-util#3]
I am using spoungycastle now. Tried to build BouncyCastle via this util and update but i stuck with it.
Build via this guide https://github.com/jbuhacoff/nodejs-mybc-util#spongycastle, but can't import it via gradle. 

If i do like this ```compile fileTree(dir: 'libs', include: ['*.jar'])```  it imports, but as org.bouncycastle and not as org.spoungycastle.

Can you help me with that?

**Comment by jbuhacoff** [comment]
If you run the postbuild script it installs the jar into your local maven repository. So you can use a line like this in gradle:

```
implementation 'com.madgag.spongycastle:bcprov-jdk15on:1.65'
```

If you keep the fileTree line make sure you don't have any other version of bouncycastle in there to avoid confusion.

**Comment by mrZizik** [comment]
So i need to setup local maven repo first?

**Comment by jbuhacoff** [comment]
When you run `mybc postbuild` it uses Maven to do that step so you already have a local maven repository. It's just a directory, default location is `~/.m2/repository`. Try adding it to your Gradle file like this:

```
repositories {
   mavenLocal()
}
```
